CREATE TABLE `my_sale_express_rules` (
  `sale_express_rules_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '仓库国家配置详情表id',
  `bs_warehouse_id` int(11) NOT NULL COMMENT '仓库id',
  `country` varchar(50) DEFAULT NULL COMMENT '国家',
  `bs_express_service_id` int(11) NOT NULL COMMENT '快递服务id',
  `sort_order` int(11) NOT NULL COMMENT '优先级',
  `max_length` varchar(255) DEFAULT NULL COMMENT '长边',
  `second_length` varchar(255) DEFAULT NULL COMMENT '次边',
  `third_length` varchar(255) DEFAULT NULL COMMENT '短边',
  `volume_weight` varchar(255) DEFAULT NULL COMMENT '体积重(长*宽*高/5000)',
  `volume_weight_v2` varchar(255) DEFAULT NULL COMMENT '体积重(长*宽*高/6000)',
  `volume_weight_v3` varchar(255) DEFAULT NULL COMMENT '体积重(长*宽*高/1000)',
  `any_length_sum` varchar(255) DEFAULT NULL COMMENT '任意两边之和',
  `perimeter` varchar(255) DEFAULT NULL COMMENT '周长',
  `us_volume_weight` varchar(255) DEFAULT NULL COMMENT '美线体积重',
  `girth` varchar(255) DEFAULT NULL COMMENT '围长',
  `gross_weight` varchar(255) DEFAULT NULL COMMENT '毛重',
  `two_width_height` varchar(255) DEFAULT NULL COMMENT '2*(宽+高)',
  `volume` varchar(255) DEFAULT NULL COMMENT '体积',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `auto_refresh_count` tinyint(1) DEFAULT NULL COMMENT '是否自动刷新数量1：是 2否',
  `default_refresh_count` int(11) DEFAULT NULL COMMENT '默认刷新数量',
  `current_count` int(11) DEFAULT NULL COMMENT '当前数量',
  `bs_platform_id` int(11) DEFAULT NULL COMMENT '平台id',
  `bs_account_id_str` text COMMENT '店铺集 用,分割',
  `postcode_str` text COMMENT '邮编前五位集 用,分割',
  `erp_sku` mediumtext COMMENT 'sku',
  `excluded_erp_sku` mediumtext COMMENT '在当前erpSku范围外',
  `enable_flag` tinyint(1) NOT NULL DEFAULT '1' COMMENT '规则启用标志 1启用  2禁用',
  `sfp_to_general` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1：普通订单规则 2：sfp转普通订单规则 3:次日达订单规则',
  `address_type` tinyint(2) DEFAULT NULL COMMENT '地址类型0:未知  1:住宅  2:商业  3:混合',
  `ctime` int(11) NOT NULL COMMENT '创建时间',
  `mtime` int(11) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`sale_express_rules_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=830 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;